server:
  port: ${PORT:8080}
  tomcat:
    max-swallow-size: 500MB
    max-http-form-post-size: 500MB


logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

spring:
  application:
    name: scholarship-system

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true

  datasource:
    url: "jdbc:mysql://shuttle.proxy.rlwy.net:27884/railway?useSSL=true&trustServerCertificate=true&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: "root"
    password: "NBawEBJxljcacrknAegKqxQDIihihNIv"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: true

jwt:
  secret: "9a67475d459d0111a9341ef970b77732a31698e5e80a068038c7f995873918f3"
  expiration: 3600000